### ISSUE TITLE
VP Feedback: Results and their display

### ISSUE THREAD

**Issue by Yanis-M** [ejp-rd-vp/VP-Testing#4]
1. enter "Duchenne muscular dystrophy" as a search term for Resource discovery
2. results are listed for Orphanet, Cellosaurus and "hpscReg"

The name of the resource "hpscReg" should be spelled "hPSCreg".

May I ask, are you using a metadata profile to get the description of hPSCreg, and if so, what is the source of this metadata profile? I see that there is a dataset schema here: https://github.com/ejp-rd-vp/query_builder_api/blob/feat/beacon_version/versions/beacon/ejprd-resources-dataset-schema.json

If, for example, the ejp-vp is using the bio.tools metadata profile for hPSCreg, and it is wrong, leading to the above error in spelling, I can change this in bio.tools.

Best
Nancy

**Comment by YingChen-bio** [comment]
![image](https://user-images.githubusercontent.com/78952904/177355879-963d7c6b-bc63-4a8f-821c-fddd82b29af4.png)
Here is the example that shows the wrong name hPSCreg as hpscReg.

**Comment by davidReinert** [comment]
Currently the metadata for connected sources is read from the resource directory and was entered manually some time ago.

**Comment by davidReinert** [comment]
I fixed the hPSCreg naming issue
